### ISSUE TITLE
add an option to allow implicit relative imports

### ISSUE THREAD

**Issue by chrisgrieser** [DetachHead/basedpyright#158] opened 2024-03-17 13:58 UTC
Hi, thanks for this project, it actually solves some headaches I had with pyright.

I tried migrating to it from pyright, but I encountered an issue with basedpyright not being able to resolve imports, that do work when using pyright.

With pyright, I have my dependencies installed in a project-relative folder `.venv`. I added these in my `pyproject.toml`, and importing works as expected.

```toml
[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "strict"
```

When I used `basedpyright` instead of `pyright`, and also add this to my pyproject.toml
```toml
[tool.basedpyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "all"
```

Then I get various errors that imports are not working:
![Pasted image 2024-03-17 at 14 58 03@2x](https://github.com/DetachHead/basedpyright/assets/73286100/bacde098-fa37-4d35-b6b3-b5caa9c6edbd)

If I leave out `[tool.basedpyright]` completely, the error for pandas disappears, but the error for the import of my own module (`strategies`) still persists:
![Pasted image 2024-03-17 at 14 57 24@2x](https://github.com/DetachHead/basedpyright/assets/73286100/a798e863-1a08-42b1-aef7-5668714bc28d)

I am using basedpyright 1.5.0 in nvim.

**Comment by DetachHead** [comment] 2024-03-17 23:11
does the issue still happen without that venv config? my projects are usually also set up with a relative local `.venv` folder but i've never used those options before. instead i just always run pyright from within the venv

**Comment by chrisgrieser** [comment] 2024-03-18 09:18
Hmm, yeah, that might be it. I have `basedpyright` not installed in the `.venv` itself, but globally (outside the project folder). Nevertheless, in the case of pyright, it also works when using a pyright binary that is outside the project folder.

I tried installing it in the venv, but get the same result there. You can try it out here in a (fairly) small repo

```bash
git clone https://github.com/chrisgrieser/axelrod-prisoner-dilemma
cd axelrod-prisoner-dilemma
make init
nvim ./prisoner-dilemma/main.py
```

**Comment by DetachHead** [comment] 2024-03-21 01:24
so i can't seem to reproduce the issue with the `pandas` import, but the other imports can be fixed by specifying the full module path, like so:
```py
from prisoner_dilemma import strategies
from prisoner_dilemma.parameters import punishment_years as punishment
from prisoner_dilemma.parameters import rounds_to_play as rounds
from prisoner_dilemma.preview import preview_html
```
or by using relative imports:
```py
from . import strategies
from .parameters import punishment_years as punishment
from .parameters import rounds_to_play as rounds
from .preview import preview_html
```

this is an additional check i added which is safer because otherwise if the script was run as a module, it would crash. [see this section of the readme for more info](https://github.com/DetachHead/basedpyright?tab=readme-ov-file#reporting-errors-on-invalid-relative-imports)

**Comment by KotlinIsland** [comment] 2024-03-21 03:45
@DetachHead fyi that solution will be incompatible with running as a script if the project root is not in the module path:

```console
> py ./prisoner-dilemma/main.py
Traceback (most recent call last):
    File "/prisoner_dilemma/prisoner_dilemma/main.py", line 1, in <module>
      from prisoner_dilemma import strategies
ModuleNotFoundError: No module named 'prisoner_dilemma'
```

@chrisgrieser Perhaps you modify the run instructions to specify `python3 -m prisoner_dilemma.main`. Or should refactor to use `__main__.py` and `python3 prisoner_dilemma`

**Comment by chrisgrieser** [comment] 2024-03-21 11:24
Hmm, while this may work, I think it would really be beneficial if basedpyright was compatible with code written using pyright. 

In this small exercise repo it's not a big deal, but in larger projects it will be quite an obstacle to refactor a lot of code just to give basedpyright a try.  And generally, adoption often hinges upon the easiness of transitioning.

**Comment by DetachHead** [comment] 2024-03-21 11:56
i should probably make it a separate option

**Comment by KotlinIsland** [comment] 2024-03-24 01:04
I think that when sibling imports (or what ever they are called) are disabled, the error on the import should say something more specific. "Sibling imports are actually invalid, here's why" or reference the docs or something.

Then, when a config option is added for it, the message could be updated to reference it.

**Closed** 2024-03-29 11:56 UTC
Labels: type checking

**Comment by DetachHead** [comment] 2024-03-29 12:34
this behavior can now be disabled in basedpyright 1.8.0:

```toml
[tool.basedpyright]
reportImplicitRelativeImport = false
```

if you want, you can also set the `typeCheckingMode` to `"strict"`, `"standard"`, or `"basic"` if you don't want to see any additional rules that aren't part of upstream pyright

**Comment by chrisgrieser** [comment] 2024-03-29 12:40
thank you!
