### ISSUE TITLE
Some unexpected behavior when using `if True`

### ISSUE THREAD

**Issue by shoucandanghehe** [DetachHead/basedpyright#844] opened 2024-11-02 12:56 UTC
environment:
- Python: 3.12.7
- basedpyright: 1.20.0
- VSCode: 1.95.1
```python
def foo() -> None: ...

bar = 1

if True:
    foo
    bar
else:
    foo
    bar
```
In the `if True` block, foo and bar behave normally.
But in the else block, bar's type is recognized as Unbound, not Literal[1]
The function signature of foo, although displayed correctly, prompts `no definition found` when you use `Go to Definition`
![image](https://github.com/user-attachments/assets/98ca1d25-a177-4e16-b0b3-5540e43c679d)
![image](https://github.com/user-attachments/assets/4da5b935-fd07-4f9b-bc1a-b778296dc6da)

**Comment by shoucandanghehe** [comment] 2024-11-02 12:58
It was initially found to be due to an `if TYPE_CHECKING:`

**Comment by DetachHead** [comment] 2024-11-03 02:36
this is caused by the fact that unreachable code is not type checked at all (or at least not properly), which is why i made the [`reportUnreachable`](https://docs.basedpyright.com/latest/benefits-over-pyright/new-diagnostic-rules/#reportunreachable) rule.

closing in favor of #7

**Closed by DetachHead** 2024-11-03 02:36 UTC
