### ISSUE TITLE
android support

### ISSUE THREAD

**Issue by abrarishere** [DetachHead/basedpyright#549] opened 2024-08-08 09:16 UTC
When i tried to install basedpyright using
```
pip install basedpyright
```

It failed because it was unable to find cmake.

So I installed cmake and it downloaded

So, Please add following lines in documentation
```
> Before installing **basedpyright** make sure you have cmake installed.
```

**Comment by KotlinIsland** [comment] 2024-08-08 11:34
Could you please add your full system+python details and installation output. Basedpyright should not require cmake

**Comment by abrarishere** [comment] 2024-08-09 00:49
System info:
Linux localhost 4.14.180-perf+ #2 SMP PREEMPT Sat Sep 3 23:17:03 CST 2022 aarch64 Android

Python info:
python -V
Python 3.11.9


I am using pip
`pip install basedpyright`

Error occurs in this process:

  `Building wheel for nodejs-wheel-binaries (pyproject.toml)`

**Comment by DetachHead** [comment] 2024-08-09 01:03
the issue is that [nodejs-wheel](https://github.com/njzjz/nodejs-wheel) (the package we use to automatically handle nodejs so that users don't have to) only bundles wheels for windows, macos and linux. but you're on android, so i would recommend raising an issue there to see if they're willing to publish wheels for android.

as a workaround, if you install nodejs manually, you can install [the basedpyright npm package](https://www.npmjs.com/package/basedpyright) instead

**Comment by abrarishere** [comment] 2024-08-09 01:39
I installed `basedpyright` using Node.js as you suggested, but will it work with Neovim? When I try to install it using `MasonInstall basedpyright`, it attempts to use pip. Could you guide me through the process?

**Comment by DetachHead** [comment] 2024-08-12 05:35
hmm, it probably won't work with anything that expects the pypi package unfortunately.

perhaps we could also publish a nodeless release which would allow users on platforms other than windows/mac/linux to use a different node binary

**Comment by abrarishere** [comment] 2024-08-12 08:04
Ok, I am waiting for that.

**Comment by KotlinIsland** [comment] 2024-08-15 22:48
@DetachHead how do we want to handle this issue? we can't do anything about nodejs-wheel here. do we want to close this issue and open "publish a nodeless release which would allow users on platforms other than windows/mac/linux to use a different node binary"?

**Comment by DetachHead** [comment] 2024-08-15 23:01
there are other issues for supporting other OS's as well. i was just gonna leave them all open until we decide on a solution

**Comment by TTsdzb** [comment] 2024-12-15 04:59
If you're using Termux I suggest manage your own language servers, instead of using mason.nvim. There are a couple of language servers couldn't be installed successfully in my experience. For example, some language servers do not provide arm64 binaries, even they can be found in pkg repositories or can be installed manually.

> as a workaround, if you install nodejs manually, you can install [the basedpyright npm package](https://www.npmjs.com/package/basedpyright) instead

You can install it through the following steps:

1. Install `basedpyright` globally through npm:

```sh
npm i -g basedpyright
```

2. Soft link executables:

```sh
cd ~/../usr/bin
ln -s ../lib/node_modules/basedpyright/index.js basedpyright
ln -s ../lib/node_modules/basedpyright/langserver.index.js basedpyright-langserver
```

Then you'll have `basedpyright` and `basedpyright-langserver` directly in your PATH, and you're ready to go without that mason package.

**Closed** 2024-12-15 09:49 UTC
Labels: node

**Comment by TTsdzb** [comment] 2024-12-15 10:28
> Then you'll have `basedpyright` and `basedpyright-langserver` directly in your PATH, and you're ready to go without that mason package.

If you're on Termux and the language server is installed but still can't be executed, check the header of the executable file:

```sh
nvim `which basedpyright`
```

You'll see the following line:

```sh
#!/usr/bin/env node
```

This will not work unless your Android distribution has `/usr/bin/env` inside. If not, change the line into:

```sh
#!/data/data/com.termux/files/usr/bin/env node
```

**Comment by TTsdzb** [comment] 2024-12-15 10:32
The Termux environment itself is way too different from a regular Linux system. If these looks too hacky, `proot-distro` can be used to create a normal Linux environment without root privilege.
