### ISSUE TITLE
Can't force CLI to read settings from pyproject.toml?

### ISSUE THREAD

**Issue by mgzenitech** [DetachHead/basedpyright#462] opened 2024-07-02 07:27 UTC
Hey guys!
First of all - amazing project.

Now, I have same issue as I had with original pyright. For some reason CLI does not read my config automatically.

Let's imagine this setup:
**pyproject.toml**
```toml
[tool.basedpyright]
extends = ".internal/configs/basedpyright.json"
```

**.internal/configs/basedpyright.json**
```json
{
  "exclude": [
    "**/.venv",
    "**/tmp"
  ],
  "pythonPlatform": "Linux",
  "reportAny": "none",
  "reportMissingTypeStubs": "none",
  "verboseOutput": true
}
```

basedpyright is installed via Poetry so let's use `poetry run basedpyright`.

It is immediatelly clear that config is not taken into account as all files within .venv are being scanned and also no verbose output.

**Comment by DetachHead** [comment] 2024-07-02 07:37
the config extending stuff kinda sucks. will investigate

**Comment by mgzenitech** [comment] 2024-07-04 06:38
side note: this issue is only with **CLI**, VSCode extension works for some reason without any issues...

**Comment by DetachHead** [comment] 2024-07-06 06:03
i can't seem to reproduce this. does it only happen when running with poetry? what happens if you activate the poetry venv and run `basedpyright` inside it?

**Comment by mgzenitech** [comment] 2024-07-08 06:35
Weird, looks like verbose output even from pyproject.toml directly
![Screenshot from 2024-07-08 09-28-54](https://github.com/DetachHead/basedpyright/assets/64852480/0f41672a-1050-406f-be89-7d3b2e26b723)
 isn't being read.

when using extends no options are being read. Even exclude, for example this is what I get when I add exclude in pyproject.toml directly:
![Screenshot from 2024-07-08 09-34-18](https://github.com/DetachHead/basedpyright/assets/64852480/74999084-fbb1-4be9-838f-ee60481dfdce)

And this is with extends:
![Screenshot from 2024-07-08 09-35-19](https://github.com/DetachHead/basedpyright/assets/64852480/be8ca606-ec04-4859-9779-feaac977dca1)

**Comment by DetachHead** [comment] 2024-07-08 08:55
i think i was able to reproduce your issue. the problem is that the `excludes` globs seem to be relative to where the config file is located. since your config file is located in `.internal/configs` you need to go up 2 directories:

```json
{
  "exclude": [
    "../../**/.venv",
    "../../**/tmp"
  ]
}
```

**Comment by mgzenitech** [comment] 2024-07-08 09:46
> i think i was able to reproduce your issue. the problem is that the `excludes` globs seem to be relative to where the config file is located. since your config file is located in `.internal/configs` you need to go up 2 directories:
> 
> ```json
> {
>   "exclude": [
>     "../../**/.venv",
>     "../../**/tmp"
>   ]
> }
> ```

you're right, holly balls. It would not even occur to me that the cwd context is being switched for extended config :O 

and what about the `"verboseOutput": true` ? I think it doesn't force cli output to be verbose as I have to append --verbose to cli calls...

**Comment by DetachHead** [comment] 2024-07-08 10:48
> and what about the `"verboseOutput": true` ? I think it doesn't force cli output to be verbose as I have to append --verbose to cli calls...

lol, it looks like that option doesn't work at all, which seems to be an upstream issue. i've raised #481 for it, but you can also raise it on the pyright repo if you want.

closing this issue since the original problem has been resolved

**Closed by DetachHead** 2024-07-08 10:48 UTC
Labels: config, awaiting response
