### ISSUE TITLE
constant length loops aren't analysed

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/basedpyright#788] opened 2024-10-17 01:12 UTC
```py
v = 0
for i in (1, 2, 3):
    v += i
reveal_type(v)  # int
```

but if we unwrap the loop:
```py
v = 0
v += 1
v += 2
v += 3
reveal_type(v)  # 6
```

**Comment by DetachHead** [comment] 2024-10-17 03:54
duplicate of #348

**Closed** 2024-10-17 03:54 UTC
Labels: type checking / linting
