### ISSUE TITLE
infer overload types

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/basedpyright#287] opened 2024-04-12 00:19 UTC
```py
@overload
def f(a: int) -> str: ...

@overload
def f(a: str) -> None: ...

def f(a):
    reveal_type(a)  # int | str
    return 1  # error: expected "str | None"
```
The types of the implementation signature should be inferred from the overload signatures.

**Comment by DetachHead** [comment] 2024-10-31 05:46
Duplicate of #179

**Closed by DetachHead** 2024-10-31 05:46 UTC
Labels: type checking / linting
