### ISSUE TITLE
Prefer conventional import aliases

### ISSUE THREAD

**Issue by jorenham** [DetachHead/basedpyright#852] opened 2024-11-06 12:22 UTC
Within the data-science corner of Python there several big libraries that are almost always imported using specific aliases, e.g. `import numpy as np`, `import matplotlib.pyplot as plt`, and `import optype as op`. 
So I think it would help a lot if the bpr plugin would recognize it if you'd type e.g. `np.int8` and auto-import `numpy as np`.
For instance in `scipy-stubs`, 

Ruff/flake8-import-conventions recognizes the following ones by default (https://docs.astral.sh/ruff/settings/#lintflake8-import-conventions):

```json
{
    "altair": "alt", 
    "matplotlib": "mpl", 
    "matplotlib.pyplot": "plt", 
    "numpy": "np", 
    "pandas": "pd", 
    "seaborn": "sns", 
    "tensorflow": "tf", 
    "tkinter": "tk", 
    "holoviews": "hv", 
    "panel": "pn", 
    "plotly.express": "px", 
    "polars": "pl", 
    "pyarrow": "pa", 
    "xml.etree.ElementTree": "ET"
}
```

While those are all correct; it's incomplete IMO, and should additionally include

stdlib:

- `ctypes` -> `ct`
- `datetime` -> `dt`
- `multiprocessing` -> `mp`
- `pprint.pprint` -> `pp` (I prefer `peepee`, but oh well)

typing stuff

- `numpy.typing` -> `npt`
- `optype` -> `op`

symbolic stuff:

- `sympy` -> `sp` (same as `scipy`, but that's ok), or `sym`
- `theano` -> `T`
- `pytensor.tensor` -> `pt`

array stuff:

- `dask.array` -> `da`
- `dask.dataframe` -> `dd`
- `xarray` -> `xr`
- `jax.numpy` -> `jnp`
- `optype.numpy` -> `onp`

science stuff:

- `scipy` -> `sp`
- `jax.scipy` -> `jsp`
- `networkx` -> `nx`
- `geopandas` -> `gpd`

(the `scipy` subpackages are often also aliased, but not in a consistent way)

machine learning stuff:

- `keras.backend` -> `K` (not a fan, but it's a thing)
- `sklearn` -> `sk`
- `skimage` -> `ski`
- `xgboost` -> `xgboost`

statistics stuff:

- `pymc3` -> `pm`
- `statsmodels.api` -> `sm`
- `statsmodels.formula.api` -> `smf`
- `statsmodels.tsa.api` -> `smt`

fast stuff:

- `numba` -> `nb`
- `numexpr` -> `ne`
- `bottleneck` -> `bn`

plotting stuff:

- `arviz` -> `az`
- `datashader` -> `ds`
- `plotly.plotly` -> `py`
- `plotly.express` -> `px`
- `plotly.graph_objects` -> `go`

(most of these I've seen being used myself, some I've only seen on https://import-as.github.io/)

**Comment by DetachHead** [comment] 2024-11-06 12:59
Duplicate of #309

**Closed by DetachHead** 2024-11-06 12:59 UTC
