### ISSUE TITLE
In-Line Hints (Variable Types)

### ISSUE THREAD

**Issue by karimlevallois** [DetachHead/basedpyright#389] opened 2024-06-01 21:51 UTC
I have just come back to my laptop after a few weeks away, updated everything and now seeing these greyed out/ghosts in line hints for variable types etc.

<img width="1680" alt="Screenshot 2024-06-01 at 22 45 10" src="https://github.com/DetachHead/basedpyright/assets/80129273/b30fdf2b-c8ac-42d4-b8af-02f74d8bae29">

Is there a way to disable them?

Many thanks, Karim

**Comment by DetachHead** [comment] 2024-06-01 22:24
these are called inlay hints. the setting to disable them depends on your editor. are you using neovim?  if so, i'm not sure because i've never used it. @baco would you happen to know?

**Comment by karimlevallois** [comment] 2024-06-01 22:29
I have always had inlay hints enabled, but I’ve never seen these before with basedpyright and they don’t show on pyright or pylance either. Is it something recently added?

**Comment by DetachHead** [comment] 2024-06-01 23:10
inlay hints were added in [version 1.5.0](https://github.com/DetachHead/basedpyright/releases/tag/v1.5.0). the reason you didn't see them in pyright is because they are a pylance-exclusive feature. unlike pylance though, they are enabled by default in basedpyright, and can be turned off in vscode by setting `"editor.inlayHints.enabled": "off"` to `"off"` in vscode.

**Comment by karimlevallois** [comment] 2024-06-01 23:14
These have only started showing the past few weeks, since I last used Neovim. I know inlay hints have been working as I’ve set diagnostics to ‘Standard’ and had that for a couple of months. These however that give details on the variables before them have never shown before. Can I disable these specific ones rather than all inlay hints?

**Comment by DetachHead** [comment] 2024-06-01 23:45
so you only want inlay hints on function parameter names but not on assignments to variables?

we haven't made any changes to inlay hints recently so im not sure what could've caused this change in behaviour. if you could create a minimal reproduction of an inlay hint that wasn't present on an older version, i can investigate.

we could also add options to customize which types of inlay hints are displayed.

**Comment by baco** [comment] 2024-06-02 03:03
Hi. I may need more info... First, some clarifications: Pylance never worked as an LSP server for Neovim (it has some proprietary stuff that the Neovim+Python community was never interested to deal with). You may be using Pyright, but Pyright on Neovim, only works as a type checker and an auto-completion engine (the part of Pyright Microsoft didn't chop off to move it to Pylance). For instance, it doesn't implement diagnostics.

I am curious on how were you able to have InlayHints “always on”.  That, as a feature, came (for all LSP servers at the same time) a few weeks ago with the release of Neovim 0.10; and no other LSP sever (despite BasedPyright) implements it for Python. Are you using CoC.nvim as a client instead of native Neovim's LSP-client feature? Are you confused with virtual-text, which is mostly used for diagnostics, because of their similarities (with InlayHints) in showing up, but not being reachable by keystrokes?

If the InlayHint is the only feature that's bothering you, you'll have to look on your Neovim's config where is being turned on, and comment out that part. Look if you have something like:

```lua
...
vim.lsp.inlay_hint.enable(true, { bufnr = bufnr })
...
```
in your settings.

Are you using a Neovim-distro? They are very common (NvimChad, AstroNvim, etc.) and the tend to turn stuff on, that the user didn't know it was there.

If you want to turn it off, maybe you can add an extra setting for doing that explicitly:

```lua
vim.lsp.inlay_hint.enable(false)
```

but that's the default, so... if you are using some Neovim distro, perhaps you can comment out the part that's turning it on in the first place.

**Comment by baco** [comment] 2024-06-02 03:12
For instance (colors may vary on your theme):
![image](https://github.com/DetachHead/basedpyright/assets/102958/f31619db-4aa4-4b77-a6f7-ed6e41f0f564)

**Comment by karimlevallois** [comment] 2024-06-02 03:58
> Hi. I may need more info... First, some clarifications: Pylance never worked as an LSP server for Neovim (it has some proprietary stuff that the Neovim+Python community was never interested to deal with). You may be using Pyright, but Pyright on Neovim, only works as a type checker and an auto-completion engine (the part of Pyright Microsoft didn't chop off to move it to Pylance). For instance, it doesn't implement diagnostics.
> 
> I am curious on how were you able to have InlayHints “always on”. That, as a feature, came (for all LSP servers at the same time) a few weeks ago with the release of Neovim 0.10; and no other LSP sever (despite BasedPyright) implements it for Python. Are you using CoC.nvim as a client instead of native Neovim's LSP-client feature? Are you confused with virtual-text, which is mostly used for diagnostics, because of their similarities (with InlayHints) in showing up, but not being reachable by keystrokes?
> 
> If the InlayHint is the only feature that's bothering you, you'll have to look on your Neovim's config where is being turned on, and comment out that part. Look if you have something like:
> 
> ```lua
> ...
> vim.lsp.inlay_hint.enable(true, { bufnr = bufnr })
> ...
> ```
> 
> in your settings.
> 
> Are you using a Neovim-distro? They are very common (NvimChad, AstroNvim, etc.) and the tend to turn stuff on, that the user didn't know it was there.
> 
> If you want to turn it off, maybe you can add an extra setting for doing that explicitly:
> 
> ```lua
> vim.lsp.inlay_hint.enable(false)
> ```
> 
> but that's the default, so... if you are using some Neovim distro, perhaps you can comment out the part that's turning it on in the first place.

Hey!

I have pylance via a rather hacky method, but it is fully functional for the most part.

I’ve been running the nightly version of Neovim for months and using standard LSP. 

Ah, I may well be thinking of virtual text then, the diagnostics element at the end of the lines in red… that mostly disappear when using ‘Standard’ for diagnostics.

Will disable inlay hints then and hopefully it will go.

Thanks for your help, much appreciated.

**Comment by baco** [comment] 2024-06-02 17:11
> I have pylance via a rather hacky method, but it is fully functional for the most part.
> 

Ok, now I am more curious on the how.  Because even VSCodium people are struggling to get it working, and VSCodium shares everything with VSCode, except for the telemetry and branding, and that's where having BasedPyright shines (in VSCodium).  But that may be topic for another thread/discussion; I'm not **that** curious, I prefer FLOSS.

> I’ve been running the nightly version of Neovim for months and using standard LSP.
> 

Ok, I understand now.  Maybe start with that, next time.  It's useful to know what set of features you may or may not have, beforehand.

> Ah, I may well be thinking of virtual text then, the diagnostics element at the end of the lines in red… that mostly disappear when using ‘Standard’ for diagnostics.
> 

Yup, that makes sense then.  BasedPyright controls the amount of diagnostics shown by the setting you mention.  In Neovim, those diagnostics are shown via the _Virtual Text_ feature; not the _Inlay Hint_ feature, rather used for inferred typing and argument's names.

> Will disable inlay hints then and hopefully it will go.
> 

Regarding that, if the setting was turned-on already, I recommend you search where is being turned on, because “on” is not the default value.  I mean, to avoid turning off, something that was just turned on.  You may save some startup time if not turning it on at all in first place.

It may also be of help, either you leave it on or off by default, to add a keymap on Neovim to toggle the state.  I have the following in Lua:

```lua
local opts = { noremap=true, silent=true, buffer=args.buf }
vim.keymap.set("n", "<Leader>ih", function()
  vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
end, opts)
```

With that, I can turn it on/off on demand pressing the `Leader` key, plus `i`, plus `h`.

> Thanks for your help, much appreciated.

No problem at all.  Thanks for reaching out.  Tell us if that solved your orignal issue so we may close this report.

**Comment by DetachHead** [comment] 2024-07-07 06:47
closing this as issue as per the above comment. feel free to raise another issue if you have any further questions

**Closed by DetachHead** 2024-07-07 06:47 UTC
Labels: language server, neovim, LSP: inlay hints, awaiting response
